[general]
static=yes
writeprotect=no

[routeshield]
exten => 1000,1,Answer()
exten => 1000,n,Wait(1)
exten => 1000,n,Playback(/var/lib/asterisk/sounds/routeshield/alert_1000)
exten => 1000,n,Hangup()

exten => 1001,1,Answer()
exten => 1001,n,Wait(1)
exten => 1001,n,Playback(/var/lib/asterisk/sounds/routeshield/alert_1001)
exten => 1001,n,Hangup()

exten => 1002,1,Answer()
exten => 1002,n,Wait(1)
exten => 1002,n,Playback(/var/lib/asterisk/sounds/routeshield/alert_1002)
exten => 1002,n,Hangup()

exten => 1003,1,Answer()
exten => 1003,n,Wait(1)
exten => 1003,n,Playback(/var/lib/asterisk/sounds/routeshield/alert_1003)
exten => 1003,n,Hangup()

exten => 1004,1,Answer()
exten => 1004,n,Wait(1)
exten => 1004,n,Playback(/var/lib/asterisk/sounds/routeshield/alert_1004)
exten => 1004,n,Hangup()
