[general]
context=unauthenticated
allowguest=no
srvlookup=no
udpbindaddr=0.0.0.0:5060
tcpenable=no

[demo]
type=friend
secret=26002
host=dynamic
context=routeshield
callerid="ORION Dispatch" <1000>
dtmfmode=rfc2833
disallow=all
allow=ulaw
allow=alaw
nat=force_rport,comedia

[gokul]
type=friend
secret=26002
host=dynamic
context=routeshield
callerid="Driver Gokul" <1000>
dtmfmode=rfc2833
disallow=all
allow=ulaw
allow=alaw
nat=force_rport,comedia

[driver1]
type=friend
secret=Routeshield@123
host=dynamic
context=routeshield
callerid="Driver 1 (Alex)" <1001>
dtmfmode=rfc2833
disallow=all
allow=ulaw
allow=alaw
nat=force_rport,comedia

[driver2]
type=friend
secret=Routeshield@123
host=dynamic
context=routeshield
callerid="Driver 2 (Ramesh)" <1002>
dtmfmode=rfc2833
disallow=all
allow=ulaw
allow=alaw
nat=force_rport,comedia

[driver3]
type=friend
secret=Routeshield@123
host=dynamic
context=routeshield
callerid="Driver 3 (Suresh)" <1003>
dtmfmode=rfc2833
disallow=all
allow=ulaw
allow=alaw
nat=force_rport,comedia

[driver4]
type=friend
secret=Routeshield@123
host=dynamic
context=routeshield
callerid="Driver 4" <1004>
dtmfmode=rfc2833
disallow=all
allow=ulaw
allow=alaw
nat=force_rport,comedia
